### ISSUE TITLE
Any dependency on node/npm version?

### ISSUE THREAD

**Issue by saniko** [5tefan/universal-react-demo#5]
npm run start fails on latest node version (7.3.0)

**Comment by 5tefan** [comment]
I was using node v6.8.0 and npm 3.10.8.

I was able to run `npm run start` successfully using node v7.4.0 (latest) with npm 4.0.5 and also node v7.3.0 with npm 3.10.10 managed with nvm. 

If you just updated your node version, make sure you delete the `node_modules` directory and re-run `npm install`. I didn't do that at first and it failed with a message about that.

**Comment by saniko** [comment]
When I changes the scripts section to:

  "server-build": "**set** NODE_ENV=prod; webpack -p --progress --config webpack.server.config.js",
   "client-build": "**set** NODE_ENV=prod; webpack -p --progress --config webpack.client.config.js",

**set** (windows) indstead of **export** (unix) i managed to run the project.

**Comment by 5tefan** [comment]
Glad you got it working! Feel free to open a pull request or continue discussion here about a cross platform solution.
