### ISSUE TITLE
How to implement to production? (question)

### ISSUE THREAD

**Issue by jasan-s** [5tefan/universal-react-demo#9]
In my research for SSR React+Redux  looked at next.js and then came to this starter.  Any guide to how to deploy this starter to production?  I plan to use Firebase cloud functions hosting for SSR but I'm unclear as to how deploy this starter event for testing.

**Comment by 5tefan** [comment]
Sorry, I'm not at all familiar with Cloud Functions for Firebase, I can't help with that. 

In general, to deploy to production, you'll want something that daemonizes the app. There are many ways to do this, here are some ideas:
- [PM2](https://github.com/Unitech/pm2) 
- [forever](https://github.com/foreverjs/forever)
- Write a [systemd unit](https://www.digitalocean.com/community/tutorials/understanding-systemd-units-and-unit-files)
- Deploy your application to a container environment, eg Kubernetes.
